language: python
python:
  - "3.4.3"
install:
  - pip install -r requirements.txt
script_before: 
  - python3 manage.py makemigrations 
  - python3 manage.py migrate 
script: 
  - python3 manage.py test
